### ISSUE TITLE
Page not displayed correctly on mobile

### ISSUE THREAD

**Issue by dj15114** [DontMash/shapez-vortex#10]
**Describe the bug**

The words on the main page and possibly pages and sections aren’t displayed correctly

**To Reproduce**
1. Open main page
2. Scroll down till the shape viewer, the blueprint viewer and the research overview section is visable

**Expected behavior**

To be correctly displayed within there seperate borders

**Screenshots**

![IMG_5646](https://github.com/user-attachments/assets/1c1a30c4-2647-4ee5-9ae7-7b259154fe2a)

**Smartphone (please complete the following information):**
 - Device: iPhone 12
 - OS: iOS 17.5.1
 - Browser: safari
 - Version 17

**Comment by DontMash** [comment]
Thanks for you bug-report.
I will work on mobile layout support in the future.
I'm currently working on updating the service to work with the most recent version of the game.
