### ISSUE TITLE
Darker Green for Wires and/or lesser brightness (option)

### ISSUE THREAD

**Issue by StingMcRay** [DontMash/shapez-vortex#12]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I like to have more darker green for wires, so they would more "shown" on the grid 
the brightness is to high for me, is there a way to set this lower/darker

**Describe alternatives you've considered**
none

**Additional context**
![afbeelding](https://github.com/user-attachments/assets/de3d65e7-3b9c-44f9-9bfb-15b1bd5c5896)

Kindly Regards
StingMcRay

**Comment by DontMash** [comment]
Thanks for your feedback!
I do not have the lighting and material properties tweaked to fit the game at the moment.
Will definitely fix that later 👍

**Comment by DontMash** [comment]
Nice looking blueprint btw 👌

**Comment by StingMcRay** [comment]
It is the 1x1 Omni Miner for Normal Scenario's including Overflow system i made with Balakin1 (DC)
and thanks for the compliment :D
