### ISSUE TITLE
Browse Blueprints

### ISSUE THREAD

**Issue by garretsimpson** [DontMash/shapez-vortex#3]
Browse Blueprints should be a top level feature.

From the home page (or anywhere) I would like to be able to navigate to Browse Blueprints.
I would like an easy way to see all of the available blueprints.  Perhaps Browse Blueprints could show a list of most recently uploaded/updated blueprint by default, and then allow the user to search or select ways to filter them.

**Comment by DontMash** [comment]
@garretsimpson thanks for your feedback!
As you correctly mentioned, I will change the default sort order to "created descending".

You can use https://shapez.soren.codes/blueprint/search to view all blueprints. It can be reached if you use the general search function (top-right) to search for blueprints.
Would you like to have a dedicated button for that?

**Comment by garretsimpson** [comment]
> It can be reached if you use the general search function (top-right) to search for blueprints.

I can't figure out how to get to https://shapez.soren.codes/blueprint/search from the search function.  You either have to enter a value (which filters the results) or click on a link, none of which go there.  Yes, I would like a way to get to an unfiltered Browse Blueprints with one button.

**Comment by DontMash** [comment]
![image](https://github.com/DontMash/shapez-vortex/assets/44289172/c830281a-4702-4911-9f28-e542aabe073e) - this will be the button.
You can search for blueprints, users, features and enter shape codes. This is a common tool/feature on modern websites.
