### ISSUE TITLE
Blueprints should include author

### ISSUE THREAD

**Issue by garretsimpson** [DontMash/shapez-vortex#4]
The properties of a blueprint should show the author (user who uploaded it).

**Comment by DontMash** [comment]
@garretsimpson the author of a blueprint is shown in the search as well as on the blueprint page e.g. https://shapez.soren.codes/blueprint/cw14hu6pqizoc5h - SamCask
Where do you think this is missing?

**Comment by garretsimpson** [comment]
The author is not shown when the user is not logged in.
But that's probably a feature.
