### ISSUE TITLE
Where is the source for the shape and blueprint viewer

### ISSUE THREAD

**Issue by evokerking1** [DontMash/shapez-vortex#41]
I mean the locations of all the files that make those work?

**Comment by DontMash** [comment]
The viewer is based on WebGL and created using a library called [threejs](https://threejs.org/) wrapped by [threlte](https://threlte.xyz/).
As we are on GitHub, you can find the implementation of the [shape view](https://github.com/DontMash/shapez-vortex/blob/main/src/lib/components/shape/ShapeView.svelte) and [blueprint view](https://github.com/DontMash/shapez-vortex/blob/main/src/lib/components/blueprint/BlueprintView.svelte) as well as the [models](https://github.com/DontMash/shapez-vortex/tree/main/static/models) in this repository.

**Comment by evokerking1** [comment]
Thanks! Will try to make an electron app for this site and utilities
