### ISSUE TITLE
Shape viewer outputs 404 error on inputs the game can accept.

### ISSUE THREAD

**Issue by Avernar** [DontMash/shapez-vortex#46]
The game will accept this: https://community-vortex.shapez2.com/shape?identifier=P-P---P-%3Acrcr--P-%3AP-cr--P-%3AP-cr--P-

Another example: https://shapez.soren.codes/shape?identifier=P-------

Both shapes are accepted by the Signal Producer, are displayed by the Display, and can be assembled (but that's irrelevant).

Is this a bug or some kind of validity check?   If the game accepts the code then the viewer should accept it.

**Comment by DontMash** [comment]
Thank you for reaching out!

This is definetly an validity check issue on my end. The game is always right :+1:

**Comment by DontMash** [comment]
@Avernar
I found the issue: The problem was caused by the fact that the viewer supports the short-hand version of shapes like `P-`. This allows a shape identifier to be a valid quad or hex shape identifier, which was determined "valid" before.
